<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>Axiom.ProtoStream.Benchmarks</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Protocols\Axiom.ProtoStream.WebSockets\Axiom.ProtoStream.WebSockets.csproj" />
  </ItemGroup>

</Project>
